services:
- docker
script:
- ./build.sh
after_success:
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
- ${TRAVIS_BUILD_DIR}/push.sh ${TRAVIS_TAG} ${TRAVIS_PULL_REQUEST_BRANCH} ${TRAVIS_BRANCH}
env:
  global:
    secure: BkL/sezVDtuDfTc/Qdh9taKB/1Vt2aWVcdIYxKNBD+ylpmKWzKOPY+UL5C7oHtgbwy0fSHR+ckX6KfYKFesZASxja61an5iN7BnnJDeLQv4Balu1OI8pRvtF8hpVUcZFzAaTm+aX4NHCRCRn6d4kSOsmvWGByv3+rIu435jA0rWWhstR1bau2aWEMjzFCRVReo13qOOluNHqlm42qch+F5VpV4YQ38V5x5v9dGv8rRdCdGhlFcvrJeS2IMabvA0N8WG/x+zjs49m0Mv/0rtNy3nVJGyYnHilwg+SZzI8dyTQTsr0EKrlRQbZhE4YD9mKWZmhlwhPYjmyzGXIP6j5l3aFbb8dNx8Z+QiSdKElJxOMnhUbZjMxFK6GWDM092ceWOqE+w0+FhL/jUN+xokq/sUhALigIvnHy9KE1TJYlyP8UKcTPN+MRDW0Wn/C8mzBpJE+SudfWj7CabKM5tv9dI3yK7NvkvLkeJCBOUDyhzyKelrpmWSOPCVKUHv6E0WnttGT+7f+J52lhqak2rTvWdUqLfogNJzHiLrRJ5WhWuBRXKq2p1wrnEcnho0mYvVgWUdYR2a/C2MHPjXTT3Tw1Yw1rzYRzfJXZ5fM68SR15hFjK17OcFFqZuwUDKkHhh7XYB7W/9TK82NSMpGzgmyQY1HnTG8HvAyTfO6idYx0Bs=
