apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: landing-page
  labels:
    application: "lsst-lsp-landing"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: landing-page
        image: lsstsqre/lsp-landing-page:latest
        ports:
        - containerPort: 8080
        env:
        - name: MOTD_URL
          value: https://raw.githubusercontent.com/lsst-dm/lsp-landing-page/master/motd/stable.md
