apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: landing-page
  namespace: default
  labels:
    application: "lsst-lsp-landing"
    version: "2.2.2"
    stage: "int"
    owner: "mcarras2"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: landing-page
        image: mgckind/lsst-lsp-landing:2.2.2
        ports:
        - containerPort: 8080
