kind: Service
apiVersion: v1
metadata:
  labels:
  labels:
    application: "lsst-lsp-landing"
    version: "2.2.1"
    stage: "dev"
    owner: "mcarras2"
    app: landing-page
  name: landing-page
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: landing-page
